# SPDX-FileCopyrightText: 2025 Deutsche Telekom IT GmbH
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: sparrow
description: A Helm chart to install Sparrow
type: application
keywords:
  - monitoring
version: 0.0.6
appVersion: "v0.5.1"
sources:
  - https://github.com/telekom/sparrow
maintainers:
  - name: y-eight
    email: maximilian.schubert@telekom.de
    url: https://www.telekom.com
  - name: puffitos
    email: bruno.bressi@telekom.de
    url: https://www.telekom.com
  - name: ntreml
    email: niklas.treml@telekom.de
    url: https://www.telekom.com
  - name: lvlcn-t
    email: tom.vendolsky@telekom.de
    url: https://www.telekom.com
